### ISSUE TITLE
Unicode in <h1> <h2>, etc, tags causes UnicodeEncodeError

### ISSUE THREAD

**Issue by ping** [PyFPDF/fpdf2#220]
Unicode in html heading tags `<h1>`, `<h2>`, etc causes an unexpected `UnicodeEncodeError`.
The same text in another tag such as `<p>` works just fine.

```python
# raises UnicodeEncodeError
pdf.write_html("<h1>Hebrew: שלום עולם</h1><p>Demo code</p>")

# works okay
pdf.write_html("<p>Hebrew: שלום עולם<</p><p>Demo code</p>")
```

```
Traceback (most recent call last):
  File "test_pdf.py", line 14, in <module>
    pdf.output("test.pdf")
  File "<snip>/venv3/lib/python3.7/site-packages/fpdf/fpdf.py", line 2400, in output
    self.close()
  File "<snip>/venv3/lib/python3.7/site-packages/fpdf/fpdf.py", line 648, in close
    self._enddoc()  # close document
  File "<snip>/venv3/lib/python3.7/site-packages/fpdf/fpdf.py", line 3123, in _enddoc
    self._put_document_outline()
  File "<snip>/venv3/lib/python3.7/site-packages/fpdf/fpdf.py", line 3037, in _put_document_outline
    self._outline, first_object_id=self._outlines_obj_id, fpdf=self
  File "<snip>/venv3/lib/python3.7/site-packages/fpdf/outline.py", line 112, in serialize_outline
    output.append(outline_item.serialize(fpdf))
  File "<snip>/venv3/lib/python3.7/site-packages/fpdf/syntax.py", line 165, in serialize
    appender(create_dictionary_string(obj_dict, open_dict="", close_dict=""))
  File "<snip>/venv3/lib/python3.7/site-packages/fpdf/fpdf.py", line 3214, in _out
    s = s.encode("latin1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 87-90: ordinal not in range(256)
```

```bash
$ python --version
Python 3.7.4
```

Code to replicate the error:

```python
from fpdf import FPDF, HTMLMixin


class PDF(FPDF, HTMLMixin):
    pass


pdf = PDF(orientation="P", unit="mm", format="A4")
pdf.add_font("DejaVuSans", fname="fonts/DejaVuSans.ttf", uni=True)
pdf.set_font("DejaVuSans")

pdf.add_page()
pdf.write_html("<h1>Hebrew: שלום עולם</h1><p>Demo code</p>")
pdf.output("test.pdf")
```

**Comment by Lucas-C** [comment]
I opened https://github.com/PyFPDF/fpdf2/pull/222 to solve this bug
