### ISSUE TITLE
creating table fails with a new registered font

### ISSUE THREAD

**Issue by aeris07** [PyFPDF/fpdf2#749]
I got below error whenever I tried to run below code to create a table with a specific font:
using FPDF2 version 2.7.1
Any help would be appreciated...

```python
from fpdf import FPDF
TABLE_DATA = (
    ("First name", "Last name", "Age", "City"),
    ("Jules", "Smith", "34", "San Juan"),
)
pdf = FPDF()
pdf.add_page()
pdf.add_font('Tr-arial', '', "TR Arial.ttf", uni=True)
pdf.set_font("Tr-Arial", size=16)
with pdf.table() as table:
       for data_row in TABLE_DATA:
              row = table.row()
              for datum in data_row:
                      row.cell(datum)
pdf.output('table.pdf')
```

ERROR:
```
Traceback (most recent call last):
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\code.py", line 90, in runcode
exec(code, self.locals)
File "", line 18, in
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 144, in exit
next(self.gen)
File "C:\Users\PC\PycharmProjects\pythonProject\venv\Lib\site-packages\fpdf\fpdf.py", line 4716, in table
table.render()
File "C:\Users\PC\PycharmProjects\pythonProject\venv\Lib\site-packages\fpdf\table.py", line 98, in render
with self._fpdf.offset_rendering() as test:
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in enter
return next(self.gen)
^^^^^^^^^^^^^^
File "C:\Users\PC\PycharmProjects\pythonProject\venv\Lib\site-packages\fpdf\fpdf.py", line 4522, in offset_rendering
recorder = FPDFRecorder(self, accept_page_break=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\PC\PycharmProjects\pythonProject\venv\Lib\site-packages\fpdf\recorder.py", line 29, in init
self._initial = deepcopy(self.pdf.dict)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
y = copier(x, memo)
^^^^^^^^^^^^^^^
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
y = copier(x, memo)
^^^^^^^^^^^^^^^
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 206, in _deepcopy_list
append(deepcopy(a, memo))
^^^^^^^^^^^^^^^^^
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
y = copier(x, memo)
^^^^^^^^^^^^^^^
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
y = copier(x, memo)
^^^^^^^^^^^^^^^
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 161, in deepcopy
rv = reductor(4)
^^^^^^^^^^^
TypeError: cannot pickle 'dict_keys' object"
```

**Comment by Lucas-C** [comment]
This is indeed a worrying bug 😢

Thank you for the report @aeris07!

I'm fixing this right now in #750 and I'm going to perform a new release 2.7.2

**Comment by Lucas-C** [comment]
@allcontributors please add @aeris07 for bug
