### ISSUE TITLE
Unicode in html tag <code>

### ISSUE THREAD

**Issue by idealism44** [PyFPDF/fpdf2#770]
I tried to write unicode in \<code\> html tag, but library converts it to `courier` font and fail.
I added font with monospace and unicode support, but it still converts to `courier` and fail.

How to write unicode in html tag \<code\>?

**Error details**
```
Traceback (most recent call last):
  File "/home/user/venv/lib/python3.9/site-packages/fpdf/fpdf.py", line 4105, in normalize_text
    return txt.encode(self.core_fonts_encoding).decode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 3-4: ordinal not in range(256)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/main.py", line 10, in <module>
    pdf.write_html(u"<code> Cześć! </code>") # Hello!
  File "/home/user/venv/lib/python3.9/site-packages/fpdf/fpdf.py", line 455, in write_html
    html2pdf.feed(text)
  File "/home/user/venv/lib/python3.9/site-packages/fpdf/html.py", line 610, in feed
    super().feed(data)
  File "/usr/lib/python3.9/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.9/html/parser.py", line 162, in goahead
    self.handle_data(unescape(rawdata[i:j]))
  File "/home/user/venv/lib/python3.9/site-packages/fpdf/html.py", line 337, in handle_data
    self.pdf.write(self.h, data)
  File "/home/user/venv/lib/python3.9/site-packages/fpdf/fpdf.py", line 261, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/user/venv/lib/python3.9/site-packages/fpdf/fpdf.py", line 3628, in write
    normalized_string = self.normalize_text(txt).replace("\r", "")
  File "/home/user/venv/lib/python3.9/site-packages/fpdf/fpdf.py", line 4107, in normalize_text
    raise FPDFUnicodeEncodingException(
fpdf.errors.FPDFUnicodeEncodingException: Character "ś" at index 3 in text is outside the range of characters supported by the font used: "courier". Please consider using a Unicode font.
```

**Minimal code**
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_font(fname='DejaVuSansMono.ttf')
pdf.set_font('DejaVuSansMono')
pdf.add_page()
pdf.write_html(u"<code> Cześć! </code>") # Hello!
```

**Environment**
* **Operating System**: Linux
* **Python version**: 3.9.2
* **`fpdf2` version used**: 2.7.3 (from branch `master`)

**Comment by gmischler** [comment]
Hi @idealism44 ,
thanks for reporting this bug.

In this context, the HTML parser makes the very old fashioned assumption that program code will only contain characters from the latin-1 charset. Given that eg. Python code has had utf-8 as default encoding for ages, that is a bit surprising. 

Unfortunately the choice of the built-in Courier font is hard coded in `HTML2FPDF.handle_starttag()`. As a short-term workaround, you could override that and handle the `tag == code` and `tag == pre` cases yourself. You also need to set `FPDF.HTML2FPDF_CLASS` to your own subclass for that to work.

You could also use the new `.set_fallback_fonts()` method to have the font of failing characters substituted automatically. The downside of that approach is that you'll end up with latin-1 vs. unicode characters in the same string being displayed in different fonts, but if they are similar enough, that may be acceptable.

An actual long-term solution would be to make the fonts used by the HTML parser for specific text categories configurable. To channel @Lucas-C : PRs welcome! :wink:
