### ISSUE TITLE
using added font results in error message

### ISSUE THREAD

**Issue by Sil68** [PyFPDF/fpdf2#828]
Hi,

I am trying to register the DejaVu fonts with a script of mine

```
from fpdf import FPDF, TitleStyle
from fpdf.fonts import FontFace

REGISTERED_FONTS = [{ 'name': 'DejaVu',
                     'path': '/usr/share/fonts/truetype/dejavu',
                     'fonts': [('DejaVuSans', '', 'DejaVuSans.ttf'),
                               ('DejaVuSans', 'B', 'DejaVuSans-Bold.ttf'),
                               ('DejaVuSans', 'I', 'DejaVuSans-Oblique.ttf'),
                               ('DejaVuSans', 'BI', 'DejaVuSans-BoldOblique.ttf'),
                               ('DejaVuSansCondensed', '', 'DejaVuSansCondensed.ttf'),
                               ('DejaVuSansCondensed', 'B', 'DejaVuSansCondensed-Bold.ttf'),
                               ('DejaVuSansCondensed', 'I', 'DejaVuSansCondensed-Oblique.ttf'),
                               ('DejaVuSansCondensed', 'BI', 'DejaVuSansCondensed-BoldOblique.ttf'),
                               ('DejaVuSansExtraLight', '', 'DejaVuSans-ExtraLight.ttf'),
                               ('DejaVuSansMono', '', 'DejaVuSansMono.ttf'),
                               ('DejaVuSansMono', 'B', 'DejaVuSansMono-Bold.ttf'),
                               ('DejaVuSansMono', 'I', 'DejaVuSansMono-Oblique.ttf'),
                               ('DejaVuSansMono', 'BI', 'DejaVuSansMono-BoldOblique.ttf'),
                               ('DejaVuSerif', '', 'DejaVuSerif.ttf'),
                               ('DejaVuSerif', 'B', 'DejaVuSerif-Bold.ttf'),
                               ('DejaVuSerif', 'I', 'DejaVuSerif-Italic.ttf'),
                               ('DejaVuSerif', 'BI', 'DejaVuSerif-BoldItalic.ttf'),
                               ('DejaVuSerifCondensed', '', 'DejaVuSerifCondensed.ttf'),
                               ('DejaVuSerifCondensed', 'B', 'DejaVuSerifCondensed-Bold.ttf'),
                               ('DejaVuSerifCondensed', 'I', 'DejaVuSerifCondensed-Italic.ttf'),
                               ('DejaVuSerifCondensed', 'BI', 'DejaVuSerifCondensed-BoldItalic.ttf'),
                               ('DejaVuMathTeXGyre', '', 'DejaVuMathTeXGyre.ttf'),] }, ]

TABLE_FONT = ['DejaVuSansCondensed', '', 10.0]
TABLE_FONT_COLOUR = [0, 0, 0]
TABLE_HEADER_FONT = ['DejaVuSansCondensed', 'B', 12.0]
TABLE_HEADER_FONT_COLOUR = [255, 255, 255]
TABLE_HEADER_BG_COLOUR = [106, 149, 25]
TABLE_CAPTION_FONT = ['DejaVuSerifCondensed', 'I', 8.0]
TABLE_CAPTION_FONT_COLOUR = [0, 0, 0]
TABLE_ALT_BG_COLOUR = [217, 217, 217]
TABLE_CELL_ALIGN = 'CENTER'
TABLE_BORDERS = 'ALL'

BLUE = (0, 0, 255)
LIGHTBLUE = (173, 216, 230)
GREY = (128, 128, 128)
GREYSCALE = 200
HEADINGS_STYLE = FontFace(family=TABLE_HEADER_FONT[0], emphasis="I", color=TABLE_HEADER_FONT_COLOUR, fill_color=GREY)

TABLE_DATA = (
   ("First name", "Last name", "Age", "City"),
   ("Jules", "Smith", "34", "San Juan"),
   ("Mary", "Ramos", "45", "Orlando"),
   ("Carlson", "Banks", "19", "Los Angeles"),
   ("Lucas", "Cimon", "31", "Saint-Mahturin-sur-Loire"),
)

pdf = FPDF()
pdf.add_page()

fbfnts = []
for rf in REGISTERED_FONTS:
   for fn in rf['fonts']:
       pdf.add_font(family=fn[0], style=fn[1], fname=f'{rf["path"]}/{fn[2]}')
       fbfnts.append(fn[0])
pdf.set_fallback_fonts(fbfnts)

pdf.set_font(*TABLE_FONT)
pdf.set_text_color(*TABLE_FONT_COLOUR)
pdf.multi_cell(w=150, h=pdf.font_size, txt='some text here')

pdf.set_font(*TABLE_HEADER_FONT)
pdf.set_text_color(*TABLE_HEADER_FONT_COLOUR)
with pdf.table(width=150, col_widths=(30, 30, 10, 30),
              text_align=("CENTER", "CENTER", "RIGHT", "LEFT"),
              line_height=2.5 * pdf.font_size,
              headings_style=HEADINGS_STYLE,
              cell_fill_color=GREYSCALE, cell_fill_mode="ROWS",
              borders_layout="MINIMAL") as table:
   for data_row in TABLE_DATA:
       row = table.row()
       for datum in data_row:
           row.cell(datum, link="https://pyfpdf.github.io/fpdf2/Tables.html")

pdf.output('table.pdf')
```

which unfortunately renders an error message

```
Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.14.0
Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0] on linux
runfile('/home/user/projects/fpdf2/test.py', wdir='/home/user/projects/fpdf2')
Traceback (most recent call last):
 File "/usr/local/miniconda3/envs/user/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
   exec(code_obj, self.user_global_ns, self.user_ns)
 File "<ipython-input-2-013550404632>", line 4, in <module>
   runfile('/home/user/projects/fpdf2/test.py', wdir='/home/user/projects/fpdf2')
 File "/opt/pycharm-community/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
   pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/opt/pycharm-community/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
   exec(compile(contents+"\n", file, 'exec'), glob, loc)
 File "/home/user/projects/fpdf2/test.py", line 77, in <module>
   with pdf.table(width=150, col_widths=(30, 30, 10, 30),
 File "/usr/local/miniconda3/envs/user/lib/python3.11/contextlib.py", line 144, in __exit__
   next(self.gen)
 File "/usr/local/miniconda3/envs/user/lib/python3.11/site-packages/fpdf/fpdf.py", line 4683, in table
   table.render()
 File "/usr/local/miniconda3/envs/user/lib/python3.11/site-packages/fpdf/table.py", line 120, in render
   raise FPDFException(
fpdf.errors.FPDFException: Using font emphasis 'I' in table headings require the corresponding font style to be added using add_font()
```

Try as I might I'm failing at figuring what I'm doing wrong.

When using the very same fonts for displaying cells or multi_cells, all works perfectly fine.

--Sil

**Comment by Sil68** [comment]
After some debugging it seems as if for the rendering of the table the font family name has to be all lowercase letters.

**Comment by Lucas-C** [comment]
> After some debugging it seems as if for the rendering of the table the font family name has to be all lowercase letters.

Interesting!
Thank you for the report @Sil68

This still seems like an annoying behaviour that I would be willing to fix.
If I understand correctly, the problem came from `FontFace(family=...)` that had to be lowercase?

**Comment by andersonhc** [comment]
On FPDF.set_font() we convert the font family to lower case before adding the style (style in upper case) and check if it exists in fpdf.fonts (fpdf.py line 1784)
On Table.render() it's using the family as is.
I believe to fix the issue we only need to change table.py line 117 from

```
font_key = family + emphasis.style
```

to 

```
font_key = family.lower() + emphasis.style
```

**Comment by Lucas-C** [comment]
I have just fixed this
